# Generated by Django 2.2 on 2019-10-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MileStore',
            new_name='Milestone',
        ),
    ]
