# Generated by Django 2.2 on 2019-10-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191015_1135'),
        ('projects', '0003_auto_20191015_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Profile'),
        ),
    ]
