# Generated by Django 2.2 on 2019-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_agent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
