# Generated by Django 2.2 on 2019-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191017_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='review_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='actual',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (1, 'Achieved'), (1, 'Failed')], default=1),
        ),
    ]
