# Generated by Django 2.2 on 2019-10-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191018_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Activity'),
        ),
    ]
