# Generated by Django 2.2 on 2019-10-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_milestone_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='input',
            name='date',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Achieved'), (3, 'Failed')], default=1),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Activity')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ExpenseCategory')),
            ],
        ),
    ]
