# Generated by Django 2.2 on 2019-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191018_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
