# Generated by Django 2.2 on 2019-10-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191015_1135'),
        ('projects', '0009_auto_20191018_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProduceInventory')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Produce')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Produce')),
            ],
        ),
    ]
